import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { buildPractice } from "./build-practice.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));

/** @type {Record<string, Array<[string, string, string]>>} */
const packs = {
  airport: [
    ["你好", "nǐ hǎo", "Hello"],
    ["谢谢", "xiè xie", "Thank you"],
    ["不用客气", "bú yòng kè qi", "You're welcome"],
    ["对不起", "duì bu qǐ", "Sorry"],
    ["没关系", "méi guān xi", "It's okay / No problem"],
    ["请问", "qǐng wèn", "Excuse me (to ask)"],
    ["我听不懂", "wǒ tīng bu dǒng", "I don't understand"],
    ["请再说一遍", "qǐng zài shuō yí biàn", "Please say that again"],
    ["你会说英语吗？", "nǐ huì shuō yīng yǔ ma?", "Do you speak English?"],
    ["这是我的护照", "zhè shì wǒ de hù zhào", "This is my passport"],
    ["我在哪里登机？", "wǒ zài nǎ lǐ dēng jī?", "Where do I board?"],
    ["登机口在哪里？", "dēng jī kǒu zài nǎ lǐ?", "Where is the gate?"],
    ["航班延误了吗？", "háng bān yán wù le ma?", "Is the flight delayed?"],
    ["我的行李在哪里取？", "wǒ de xíng li zài nǎ lǐ qǔ?", "Where do I claim my baggage?"],
    ["我的行李丢了", "wǒ de xíng li diū le", "I lost my luggage"],
    ["这是入境卡", "zhè shì rù jìng kǎ", "This is the arrival card"],
    ["我来旅游", "wǒ lái lǚ yóu", "I'm here for tourism"],
    ["我住酒店", "wǒ zhù jiǔ diàn", "I'm staying at a hotel"],
    ["停留多久？", "tíng liú duō jiǔ?", "How long will you stay?"],
    ["一个星期", "yí gè xīng qī", "One week"],
    ["两周", "liǎng zhōu", "Two weeks"],
    ["请帮我一下", "qǐng bāng wǒ yí xià", "Please help me"],
    ["洗手间在哪里？", "xǐ shǒu jiān zài nǎ lǐ?", "Where is the restroom?"],
    ["免费 Wi‑Fi 有吗？", "miǎn fèi Wi‑Fi yǒu ma?", "Is there free Wi‑Fi?"],
    ["这里可以换钱吗？", "zhè lǐ kě yǐ huàn qián ma?", "Can I exchange money here?"],
    ["机场大巴在哪里？", "jī chǎng dà bā zài nǎ lǐ?", "Where is the airport bus?"],
    ["出租车在哪里？", "chū zū chē zài nǎ lǐ?", "Where are the taxis?"],
    ["地铁站怎么走？", "dì tiě zhàn zěn me zǒu?", "How do I get to the subway?"],
    ["我要去市区", "wǒ yào qù shì qū", "I want to go downtown"],
    ["请给我一张地图", "qǐng gěi wǒ yì zhāng dì tú", "Please give me a map"],
  ],
  taxi: [
    ["打车", "dǎ chē", "Take a taxi"],
    ["去这里", "qù zhè lǐ", "Go here"],
    ["请到这个地址", "qǐng dào zhè ge dì zhǐ", "Please go to this address"],
    ["多少钱？", "duō shao qián?", "How much is it?"],
    ["太贵了", "tài guì le", "That's too expensive"],
    ["可以用支付宝吗？", "kě yǐ yòng zhī fù bǎo ma?", "Can I use Alipay?"],
    ["可以刷卡吗？", "kě yǐ shuā kǎ ma?", "Can I pay by card?"],
    ["请打表", "qǐng dǎ biǎo", "Please use the meter"],
    ["请慢一点", "qǐng màn yì diǎn", "Please slow down"],
    ["请在这里停", "qǐng zài zhè lǐ tíng", "Please stop here"],
    ["左转", "zuǒ zhuǎn", "Turn left"],
    ["右转", "yòu zhuǎn", "Turn right"],
    ["直行", "zhí xíng", "Go straight"],
    ["前面红灯", "qián miàn hóng dēng", "Red light ahead"],
    ["我要去火车站", "wǒ yào qù huǒ chē zhàn", "I want to go to the train station"],
    ["我要去地铁站", "wǒ yào qù dì tiě zhàn", "I want to go to the subway station"],
    ["附近有地铁吗？", "fù jìn yǒu dì tiě ma?", "Is there a subway nearby?"],
    ["下一站是哪里？", "xià yí zhàn shì nǎ lǐ?", "What is the next stop?"],
    ["我在哪里下车？", "wǒ zài nǎ lǐ xià chē?", "Where should I get off?"],
    ["请告诉我到了", "qǐng gào su wǒ dào le", "Please tell me when we arrive"],
    ["堵车了吗？", "dǔ chē le ma?", "Is there a traffic jam?"],
    ["大概多久到？", "dà gài duō jiǔ dào?", "About how long will it take?"],
    ["我要一张票", "wǒ yào yì zhāng piào", "I want one ticket"],
    ["单程票", "dān chéng piào", "One-way ticket"],
    ["往返票", "wǎng fǎn piào", "Round-trip ticket"],
    ["这是我的座位吗？", "zhè shì wǒ de zuò wèi ma?", "Is this my seat?"],
    ["请扫这个码", "qǐng sǎo zhè ge mǎ", "Please scan this code"],
    ["网约车在这里等", "wǎng yuē chē zài zhè lǐ děng", "The ride-hail is waiting here"],
    ["司机师傅你好", "sī jī shī fu nǐ hǎo", "Hello, driver"],
    ["麻烦您了", "má fan nín le", "Thank you for the trouble"],
  ],
  hotel: [
    ["我有预订", "wǒ yǒu yù dìng", "I have a reservation"],
    ["我的名字是……", "wǒ de míng zi shì…", "My name is…"],
    ["入住", "rù zhù", "Check in"],
    ["退房", "tuì fáng", "Check out"],
    ["有空房吗？", "yǒu kòng fáng ma?", "Do you have any rooms available?"],
    ["一晚多少钱？", "yì wǎn duō shao qián?", "How much per night?"],
    ["我想要一间双人房", "wǒ xiǎng yào yì jiān shuāng rén fáng", "I'd like a double room"],
    ["有没有单人房？", "yǒu méi yǒu dān rén fáng?", "Do you have a single room?"],
    ["包括早餐吗？", "bāo kuò zǎo cān ma?", "Is breakfast included?"],
    ["Wi‑Fi 密码是多少？", "Wi‑Fi mì mǎ shì duō shao?", "What's the Wi‑Fi password?"],
    ["电梯在哪里？", "diàn tī zài nǎ lǐ?", "Where is the elevator?"],
    ["我的房间号是……", "wǒ de fáng jiān hào shì…", "My room number is…"],
    ["钥匙坏了", "yào shi huài le", "The key doesn't work"],
    ["空调不制冷", "kōng tiáo bù zhì lěng", "The air conditioner isn't cooling"],
    ["没有热水", "méi yǒu rè shuǐ", "There's no hot water"],
    ["可以换房间吗？", "kě yǐ huàn fáng jiān ma?", "Can I change rooms?"],
    ["请叫出租车", "qǐng jiào chū zū chē", "Please call a taxi"],
    ["行李可以寄存吗？", "xíng li kě yǐ jì cún ma?", "Can I store my luggage?"],
    ["早餐几点开始？", "zǎo cān jǐ diǎn kāi shǐ?", "What time does breakfast start?"],
    ["健身房在几楼？", "jiàn shēn fáng zài jǐ lóu?", "Which floor is the gym?"],
    ["附近有餐厅吗？", "fù jìn yǒu cān tīng ma?", "Are there restaurants nearby?"],
    ["请开发票", "qǐng kāi fā piào", "Please give me an invoice/receipt"],
    ["我要续住一晚", "wǒ yào xù zhù yì wǎn", "I'd like to stay one more night"],
    ["可以晚点退房吗？", "kě yǐ wǎn diǎn tuì fáng ma?", "Can I have a late checkout?"],
    ["保险箱怎么用？", "bǎo xiǎn xiāng zěn me yòng?", "How do I use the safe?"],
    ["毛巾可以换吗？", "máo jīn kě yǐ huàn ma?", "Can I get clean towels?"],
    ["请保持安静", "qǐng bǎo chí ān jìng", "Please keep quiet"],
    ["前台电话是多少？", "qián tái diàn huà shì duō shao?", "What's the front desk number?"],
    ["我把东西落在房间了", "wǒ bǎ dōng xi là zài fáng jiān le", "I left something in the room"],
    ["谢谢，再见", "xiè xie, zài jiàn", "Thank you, goodbye"],
  ],
  restaurant: [
    ["有英文菜单吗？", "yǒu yīng wén cài dān ma?", "Do you have an English menu?"],
    ["我要这份", "wǒ yào zhè fèn", "I'll have this one"],
    ["推荐什么？", "tuī jiàn shén me?", "What do you recommend?"],
    ["不要太辣", "bú yào tài là", "Not too spicy"],
    ["我不吃辣", "wǒ bù chī là", "I don't eat spicy food"],
    ["我吃素", "wǒ chī sù", "I'm vegetarian"],
    ["我对花生过敏", "wǒ duì huā shēng guò mǐn", "I'm allergic to peanuts"],
    ["不要香菜", "bú yào xiāng cài", "No cilantro"],
    ["一碗米饭", "yì wǎn mǐ fàn", "One bowl of rice"],
    ["两杯水", "liǎng bēi shuǐ", "Two glasses of water"],
    ["一杯啤酒", "yì bēi pí jiǔ", "A beer"],
    ["热的", "rè de", "Hot"],
    ["冰的", "bīng de", "Iced"],
    ["打包", "dǎ bāo", "Takeaway / to go"],
    ["买单", "mǎi dān", "Check, please"],
    ["可以分开付吗？", "kě yǐ fēn kāi fù ma?", "Can we split the bill?"],
    ["好吃！", "hǎo chī!", "Delicious!"],
    ["有点咸", "yǒu diǎn xián", "A bit salty"],
    ["再来一份", "zài lái yí fèn", "One more portion"],
    ["筷子", "kuài zi", "Chopsticks"],
    ["勺子", "sháo zi", "Spoon"],
    ["叉子", "chā zi", "Fork"],
    ["餐巾纸", "cān jīn zhǐ", "Napkin"],
    ["洗手间在哪儿？", "xǐ shǒu jiān zài nǎr?", "Where's the restroom?"],
    ["座位有吗？", "zuò wèi yǒu ma?", "Do you have a table?"],
    ["两位", "liǎng wèi", "Table for two"],
    ["我们等一下", "wǒ men děng yí xià", "We'll wait a moment"],
    ["这是什么菜？", "zhè shì shén me cài?", "What dish is this?"],
    ["多少卡路里不重要", "duō shao kǎ lù lǐ bù zhòng yào", "Calories don't matter"],
    ["谢谢招待", "xiè xie zhāo dài", "Thanks for having us"],
  ],
  shopping: [
    ["这个多少钱？", "zhè ge duō shao qián?", "How much is this?"],
    ["可以便宜一点吗？", "kě yǐ pián yi yì diǎn ma?", "Can you make it cheaper?"],
    ["太贵了", "tài guì le", "Too expensive"],
    ["我再看看", "wǒ zài kàn kan", "I'll look around more"],
    ["我要这个", "wǒ yào zhè ge", "I want this one"],
    ["有小一号吗？", "yǒu xiǎo yì hào ma?", "Do you have a smaller size?"],
    ["有大一号吗？", "yǒu dà yì hào ma?", "Do you have a larger size?"],
    ["可以试穿吗？", "kě yǐ shì chuān ma?", "Can I try it on?"],
    ["试衣间在哪里？", "shì yī jiān zài nǎ lǐ?", "Where is the fitting room?"],
    ["有别的颜色吗？", "yǒu bié de yán sè ma?", "Do you have another color?"],
    ["可以刷卡吗？", "kě yǐ shuā kǎ ma?", "Can I pay by card?"],
    ["支持微信支付吗？", "zhī chí wēi xìn zhī fù ma?", "Do you take WeChat Pay?"],
    ["请给我袋子", "qǐng gěi wǒ dài zi", "Please give me a bag"],
    ["开发票", "kāi fā piào", "I need a receipt/invoice"],
    ["可以退货吗？", "kě yǐ tuì huò ma?", "Can I return this?"],
    ["保修吗？", "bǎo xiū ma?", "Is there a warranty?"],
    ["专柜在几楼？", "zhuān guì zài jǐ lóu?", "Which floor is the counter?"],
    ["超市在哪里？", "chāo shì zài nǎ lǐ?", "Where is the supermarket?"],
    ["便利店", "biàn lì diàn", "Convenience store"],
    ["这个怎么卖？", "zhè ge zěn me mài?", "How is this sold / priced?"],
    ["称一下", "chēng yí xià", "Please weigh it"],
    ["半斤", "bàn jīn", "About 250g (half jin)"],
    ["一斤", "yì jīn", "About 500g (one jin)"],
    ["新鲜吗？", "xīn xiān ma?", "Is it fresh?"],
    ["我只要一点", "wǒ zhǐ yào yì diǎn", "I only want a little"],
    ["礼物可以包装吗？", "lǐ wù kě yǐ bāo zhuāng ma?", "Can you gift-wrap it?"],
    ["打几折？", "dǎ jǐ zhé?", "What discount is it?"],
    ["会员卡有优惠吗？", "huì yuán kǎ yǒu yōu huì ma?", "Is there a member discount?"],
    ["我不要塑料袋", "wǒ bú yào sù liào dài", "I don't need a plastic bag"],
    ["结账", "jié zhàng", "Checkout"],
  ],
  money: [
    ["多少钱？", "duō shao qián?", "How much is it?"],
    ["太贵了", "tài guì le", "That's too expensive"],
    ["便宜一点", "pián yi yì diǎn", "A bit cheaper"],
    ["一共多少？", "yí gòng duō shao?", "How much in total?"],
    ["我只有一百块", "wǒ zhǐ yǒu yì bǎi kuài", "I only have 100 yuan"],
    ["找钱", "zhǎo qián", "Keep the change / give me change"],
    ["不用找了", "bú yòng zhǎo le", "Keep the change"],
    ["可以破开吗？", "kě yǐ pò kāi ma?", "Can you break this bill?"],
    ["一块", "yí kuài", "One yuan"],
    ["十块", "shí kuài", "Ten yuan"],
    ["五十", "wǔ shí", "Fifty"],
    ["一百", "yì bǎi", "One hundred"],
    ["两百", "liǎng bǎi", "Two hundred"],
    ["一千", "yì qiān", "One thousand"],
    ["零", "líng", "Zero"],
    ["一、二、三", "yī, èr, sān", "One, two, three"],
    ["四、五、六", "sì, wǔ, liù", "Four, five, six"],
    ["七、八、九、十", "qī, bā, jiǔ, shí", "Seven, eight, nine, ten"],
    ["半价", "bàn jià", "Half price"],
    ["打折吗？", "dǎ zhé ma?", "Is there a discount?"],
    ["人民币", "rén mín bì", "Chinese yuan (RMB)"],
    ["现金", "xiàn jīn", "Cash"],
    ["收据", "shōu jù", "Receipt"],
    ["这个价包括税吗？", "zhè ge jià bāo kuò shuì ma?", "Does this price include tax?"],
    ["我没带够现金", "wǒ méi dài gòu xiàn jīn", "I don't have enough cash"],
  ],
  directions: [
    ["请问怎么走？", "qǐng wèn zěn me zǒu?", "Excuse me, how do I get there?"],
    ["在哪里？", "zài nǎ lǐ?", "Where is it?"],
    ["近吗？", "jìn ma?", "Is it nearby?"],
    ["远吗？", "yuǎn ma?", "Is it far?"],
    ["左边", "zuǒ biān", "On the left"],
    ["右边", "yòu biān", "On the right"],
    ["前面", "qián miàn", "Ahead / in front"],
    ["后面", "hòu miàn", "Behind"],
    ["对面", "duì miàn", "Across from / opposite"],
    ["拐角", "guǎi jiǎo", "Corner"],
    ["一直走", "yì zhí zǒu", "Go straight"],
    ["过马路", "guò mǎ lù", "Cross the street"],
    ["红绿灯", "hóng lǜ dēng", "Traffic light"],
    ["出口", "chū kǒu", "Exit"],
    ["入口", "rù kǒu", "Entrance"],
    ["附近有银行吗？", "fù jìn yǒu yín háng ma?", "Is there a bank nearby?"],
    ["附近有地铁吗？", "fù jìn yǒu dì tiě ma?", "Is there a subway nearby?"],
    ["我迷路了", "wǒ mí lù le", "I'm lost"],
    ["可以在地图上指给我看吗？", "kě yǐ zài dì tú shàng zhǐ gěi wǒ kàn ma?", "Can you show me on the map?"],
    ["走路多久？", "zǒu lù duō jiǔ?", "How long on foot?"],
    ["坐车多久？", "zuò chē duō jiǔ?", "How long by car/transit?"],
    ["往北走", "wǎng běi zǒu", "Go north"],
    ["往南走", "wǎng nán zǒu", "Go south"],
    ["在二楼", "zài èr lóu", "On the second floor"],
    ["就在那边", "jiù zài nà biān", "It's right over there"],
  ],
  mobile: [
    ["我需要一张电话卡", "wǒ xū yào yì zhāng diàn huà kǎ", "I need a phone SIM card"],
    ["有没有游客卡？", "yǒu méi yǒu yóu kè kǎ?", "Do you have a tourist SIM?"],
    ["流量多吗？", "liú liàng duō ma?", "Is there a lot of data?"],
    ["可以上网吗？", "kě yǐ shàng wǎng ma?", "Can I get online?"],
    ["信号不好", "xìn hào bù hǎo", "The signal is bad"],
    ["没有网", "méi yǒu wǎng", "There's no internet"],
    ["Wi‑Fi 密码是多少？", "Wi‑Fi mì mǎ shì duō shao?", "What's the Wi‑Fi password?"],
    ["怎么开热点？", "zěn me kāi rè diǎn?", "How do I turn on a hotspot?"],
    ["我收不到验证码", "wǒ shōu bu dào yàn zhèng mǎ", "I can't receive the verification code"],
    ["请发短信", "qǐng fā duǎn xìn", "Please send a text message"],
    ["我的号码是……", "wǒ de hào mǎ shì…", "My number is…"],
    ["信号满格吗？", "xìn hào mǎn gé ma?", "Is there full signal?"],
    ["这里有充电的地方吗？", "zhè lǐ yǒu chōng diàn de dì fang ma?", "Is there a place to charge here?"],
    ["充电宝可以租吗？", "chōng diàn bǎo kě yǐ zū ma?", "Can I rent a power bank?"],
    ["套餐包含通话吗？", "tào cān bāo hán tōng huà ma?", "Does the plan include calls?"],
    ["可以用几天？", "kě yǐ yòng jǐ tiān?", "How many days can I use it?"],
    ["到期了怎么办？", "dào qī le zěn me bàn?", "What happens when it expires?"],
    ["帮我激活一下", "bāng wǒ jī huó yí xià", "Please help me activate it"],
    ["护照要复印吗？", "hù zhào yào fù yìn ma?", "Do you need a passport copy?"],
    ["我手机没电了", "wǒ shǒu jī méi diàn le", "My phone is out of battery"],
    ["扫码连 Wi‑Fi", "sǎo mǎ lián Wi‑Fi", "Scan to connect to Wi‑Fi"],
    ["网络很慢", "wǎng luò hěn màn", "The network is very slow"],
    ["能打电话到国外吗？", "néng dǎ diàn huà dào guó wài ma?", "Can I call abroad?"],
    ["客服电话是多少？", "kè fú diàn huà shì duō shao?", "What's the customer service number?"],
    ["麻烦帮我设置一下", "má fan bāng wǒ shè zhì yí xià", "Please help me set it up"],
  ],
  payment: [
    ["可以扫码支付吗？", "kě yǐ sǎo mǎ zhī fù ma?", "Can I pay by scanning a QR code?"],
    ["支持微信支付吗？", "zhī chí wēi xìn zhī fù ma?", "Do you take WeChat Pay?"],
    ["支持支付宝吗？", "zhī chí zhī fù bǎo ma?", "Do you take Alipay?"],
    ["我扫你还是你扫我？", "wǒ sǎo nǐ hái shì nǐ sǎo wǒ?", "Do I scan you, or do you scan me?"],
    ["这是付款码", "zhè shì fù kuǎn mǎ", "This is my payment code"],
    ["请出示收款码", "qǐng chū shì shōu kuǎn mǎ", "Please show the collection QR code"],
    ["支付失败了", "zhī fù shī bài le", "The payment failed"],
    ["我还没绑定银行卡", "wǒ hái méi bǎng dìng yín háng kǎ", "I haven't linked a bank card yet"],
    ["外国人可以用吗？", "wài guó rén kě yǐ yòng ma?", "Can foreigners use this?"],
    ["只用现金可以吗？", "zhǐ yòng xiàn jīn kě yǐ ma?", "Can I pay cash only?"],
    ["可以刷卡吗？", "kě yǐ shuā kǎ ma?", "Can I pay by card?"],
    ["Visa 可以吗？", "Visa kě yǐ ma?", "Is Visa OK?"],
    ["付款成功了吗？", "fù kuǎn chéng gōng le ma?", "Did the payment go through?"],
    ["请再扫一次", "qǐng zài sǎo yí cì", "Please scan again"],
    ["二维码过期了", "èr wéi mǎ guò qī le", "The QR code expired"],
    ["我没带手机", "wǒ méi dài shǒu jī", "I didn't bring my phone"],
    ["可以转账吗？", "kě yǐ zhuǎn zhàng ma?", "Can I transfer money?"],
    ["分开付", "fēn kāi fù", "Pay separately"],
    ["我来付", "wǒ lái fù", "I'll pay"],
    ["已经付过了", "yǐ jīng fù guò le", "It's already paid"],
    ["退款多久到？", "tuì kuǎn duō jiǔ dào?", "How long for the refund?"],
    ["账单发我一下", "zhàng dān fā wǒ yí xià", "Please send me the bill"],
    ["显示支付中", "xiǎn shì zhī fù zhōng", "It says payment processing"],
    ["需要人脸识别", "xū yào rén liàn shí bié", "Face verification is required"],
    ["我开不开通？", "wǒ kāi bu kāi tōng?", "Should I enable/set this up?"],
  ],
  train: [
    ["我要买火车票", "wǒ yào mǎi huǒ chē piào", "I want to buy a train ticket"],
    ["高铁票", "gāo tiě piào", "High-speed rail ticket"],
    ["有今天的票吗？", "yǒu jīn tiān de piào ma?", "Are there tickets for today?"],
    ["二等座", "èr děng zuò", "Second-class seat"],
    ["一等座", "yī děng zuò", "First-class seat"],
    ["站票", "zhàn piào", "Standing ticket"],
    ["车次是多少？", "chē cì shì duō shao?", "What's the train number?"],
    ["几号站台？", "jǐ hào zhàn tái?", "Which platform?"],
    ["检票口在哪里？", "jiǎn piào kǒu zài nǎ lǐ?", "Where is the ticket gate?"],
    ["什么时候发车？", "shén me shí hou fā chē?", "When does it depart?"],
    ["什么时候到？", "shén me shí hou dào?", "When does it arrive?"],
    ["座位号是多少？", "zuò wèi hào shì duō shao?", "What's the seat number?"],
    ["我的车票在手机上", "wǒ de chē piào zài shǒu jī shàng", "My ticket is on my phone"],
    ["需要取票吗？", "xū yào qǔ piào ma?", "Do I need to collect a paper ticket?"],
    ["可以改签吗？", "kě yǐ gǎi qiān ma?", "Can I change the ticket?"],
    ["可以退票吗？", "kě yǐ tuì piào ma?", "Can I refund the ticket?"],
    ["列车晚点了吗？", "liè chē wǎn diǎn le ma?", "Is the train delayed?"],
    ["这是南站还是北站？", "zhè shì nán zhàn hái shì běi zhàn?", "Is this the South or North station?"],
    ["请帮我看一下车厢", "qǐng bāng wǒ kàn yí xià chē xiāng", "Please help me find the carriage"],
    ["行李可以带上火车吗？", "xíng li kě yǐ dài shàng huǒ chē ma?", "Can I take luggage on the train?"],
    ["实名制购票", "shí míng zhì gòu piào", "Real-name ticket purchase"],
    ["护照可以进站吗？", "hù zhào kě yǐ jìn zhàn ma?", "Can I enter with a passport?"],
    ["候车室在哪里？", "hòu chē shì zài nǎ lǐ?", "Where is the waiting hall?"],
    ["下一班是几点？", "xià yì bān shì jǐ diǎn?", "What time is the next one?"],
    ["我坐过站了", "wǒ zuò guò zhàn le", "I missed my stop"],
  ],
  sightseeing: [
    ["门票多少钱？", "mén piào duō shao qián?", "How much is the admission ticket?"],
    ["有学生票吗？", "yǒu xué shēng piào ma?", "Is there a student ticket?"],
    ["需要预约吗？", "xū yào yù yuē ma?", "Do I need a reservation?"],
    ["今天开放吗？", "jīn tiān kāi fàng ma?", "Is it open today?"],
    ["营业时间是几点到几点？", "yíng yè shí jiān shì jǐ diǎn dào jǐ diǎn?", "What are the opening hours?"],
    ["最晚几点入场？", "zuì wǎn jǐ diǎn rù chǎng?", "What's the latest entry time?"],
    ["可以拍照吗？", "kě yǐ pāi zhào ma?", "Can I take photos?"],
    ["可以摄像吗？", "kě yǐ shè xiàng ma?", "Can I record video?"],
    ["导游讲解有英文吗？", "dǎo yóu jiǎng jiě yǒu yīng wén ma?", "Is there an English guided tour?"],
    ["语音导览怎么租？", "yǔ yīn dǎo lǎn zěn me zū?", "How do I rent an audio guide?"],
    ["出口在哪里？", "chū kǒu zài nǎ lǐ?", "Where is the exit?"],
    ["这个景点值得去吗？", "zhè ge jǐng diǎn zhí dé qù ma?", "Is this attraction worth visiting?"],
    ["人多吗？", "rén duō ma?", "Is it crowded?"],
    ["要排队多久？", "yào pái duì duō jiǔ?", "How long is the wait?"],
    ["套票包括什么？", "tào piào bāo kuò shén me?", "What does the combo ticket include?"],
    ["可以退票吗？", "kě yǐ tuì piào ma?", "Can I get a refund?"],
    ["景区地图有吗？", "jǐng qū dì tú yǒu ma?", "Do you have a park map?"],
    ["洗手间在哪里？", "xǐ shǒu jiān zài nǎ lǐ?", "Where is the restroom?"],
    ["可以带食物进去吗？", "kě yǐ dài shí wù jìn qù ma?", "Can I bring food inside?"],
    ["这里可以寄存行李吗？", "zhè lǐ kě yǐ jì cún xíng li ma?", "Can I store luggage here?"],
    ["请帮我们拍一张", "qǐng bāng wǒ men pāi yì zhāng", "Please take a photo for us"],
    ["网红打卡点在哪？", "wǎng hóng dǎ kǎ diǎn zài nǎ?", "Where's the popular photo spot?"],
    ["下山怎么走？", "xià shān zěn me zǒu?", "How do I go down the mountain?"],
    ["缆车在哪里？", "lǎn chē zài nǎ lǐ?", "Where is the cable car?"],
    ["我有电子票", "wǒ yǒu diàn zǐ piào", "I have an e-ticket"],
  ],
  emergency: [
    ["救命！", "jiù mìng!", "Help!"],
    ["请帮我！", "qǐng bāng wǒ!", "Please help me!"],
    ["我需要警察", "wǒ xū yào jǐng chá", "I need the police"],
    ["请叫救护车", "qǐng jiào jiù hù chē", "Please call an ambulance"],
    ["我生病了", "wǒ shēng bìng le", "I'm sick"],
    ["我受伤了", "wǒ shòu shāng le", "I'm injured"],
    ["医院在哪里？", "yī yuàn zài nǎ lǐ?", "Where is the hospital?"],
    ["药店在哪里？", "yào diàn zài nǎ lǐ?", "Where is the pharmacy?"],
    ["我头痛", "wǒ tóu tòng", "I have a headache"],
    ["我肚子痛", "wǒ dù zi tòng", "I have a stomachache"],
    ["我过敏", "wǒ guò mǐn", "I have an allergy"],
    ["我的护照丢了", "wǒ de hù zhào diū le", "I lost my passport"],
    ["我的手机丢了", "wǒ de shǒu jī diū le", "I lost my phone"],
    ["我的钱包被偷了", "wǒ de qián bāo bèi tōu le", "My wallet was stolen"],
    ["请联系我的大使馆", "qǐng lián xì wǒ de dà shǐ guǎn", "Please contact my embassy"],
    ["这里不安全", "zhè lǐ bù ān quán", "This place is not safe"],
    ["我迷路了", "wǒ mí lù le", "I'm lost"],
    ["我找不到酒店", "wǒ zhǎo bu dào jiǔ diàn", "I can't find my hotel"],
    ["紧急出口", "jǐn jí chū kǒu", "Emergency exit"],
    ["火警", "huǒ jǐng", "Fire alarm / fire"],
    ["请慢点说", "qǐng màn diǎn shuō", "Please speak slowly"],
    ["我需要翻译", "wǒ xū yào fān yì", "I need a translator"],
    ["这是紧急情况", "zhè shì jǐn jí qíng kuàng", "This is an emergency"],
    ["我感觉不舒服", "wǒ gǎn jué bù shū fu", "I don't feel well"],
    ["有人会英语吗？", "yǒu rén huì yīng yǔ ma?", "Does anyone speak English?"],
    ["请打电话给……", "qǐng dǎ diàn huà gěi…", "Please call…"],
    ["我的电话号码是……", "wǒ de diàn huà hào mǎ shì…", "My phone number is…"],
    ["等一下", "děng yí xià", "Wait a moment"],
    ["危险！", "wēi xiǎn!", "Danger!"],
    ["我没事", "wǒ méi shì", "I'm fine / I'm okay"],
  ],
  smalltalk: [
    ["你好吗？", "nǐ hǎo ma?", "How are you?"],
    ["我很好", "wǒ hěn hǎo", "I'm fine"],
    ["认识你很高兴", "rèn shi nǐ hěn gāo xìng", "Nice to meet you"],
    ["你叫什么名字？", "nǐ jiào shén me míng zi?", "What's your name?"],
    ["我叫……", "wǒ jiào…", "My name is…"],
    ["你是哪国人？", "nǐ shì nǎ guó rén?", "What nationality are you?"],
    ["我是美国人", "wǒ shì měi guó rén", "I'm American"],
    ["我是英国人", "wǒ shì yīng guó rén", "I'm British"],
    ["第一次来中国", "dì yī cì lái zhōng guó", "First time in China"],
    ["中国很大", "zhōng guó hěn dà", "China is very big"],
    ["这里很漂亮", "zhè lǐ hěn piào liang", "It's beautiful here"],
    ["今天天气很好", "jīn tiān tiān qì hěn hǎo", "The weather is nice today"],
    ["太热了", "tài rè le", "It's too hot"],
    ["有点冷", "yǒu diǎn lěng", "It's a bit cold"],
    ["你喜欢中国菜吗？", "nǐ xǐ huan zhōng guó cài ma?", "Do you like Chinese food?"],
    ["我喜欢", "wǒ xǐ huan", "I like it"],
    ["一般般", "yì bān bān", "So-so"],
    ["加油！", "jiā yóu!", "Come on! / You got this!"],
    ["辛苦了", "xīn kǔ le", "Thanks for your hard work"],
    ["慢慢吃", "màn màn chī", "Take your time eating"],
    ["再见", "zài jiàn", "Goodbye"],
    ["明天见", "míng tiān jiàn", "See you tomorrow"],
    ["晚安", "wǎn ān", "Good night"],
    ["早上好", "zǎo shang hǎo", "Good morning"],
    ["不好意思打扰了", "bù hǎo yì si dǎ rǎo le", "Sorry to bother you"],
    ["可以合影吗？", "kě yǐ hé yǐng ma?", "Can we take a photo together?"],
    ["太棒了！", "tài bàng le!", "Awesome!"],
    ["没问题", "méi wèn tí", "No problem"],
    ["我不知道", "wǒ bù zhī dào", "I don't know"],
    ["稍等一下", "shāo děng yí xià", "Just a moment"],
  ],
};

const FREE_PER_SCENE = 8;
const phrases = [];
let order = 1;
let freeCount = 0;

for (const [scene, rows] of Object.entries(packs)) {
  rows.forEach(([zh, pinyin, en], i) => {
    const free = i < FREE_PER_SCENE;
    if (free) freeCount += 1;
    phrases.push({
      id: `${scene}-${String(i + 1).padStart(3, "0")}`,
      scene,
      zh,
      pinyin,
      en,
      order: order++,
      free,
      practice: buildPractice(zh, pinyin, en),
    });
  });
}

const out = join(__dirname, "..", "content", "phrases.json");
mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, JSON.stringify({ phrases }, null, 2) + "\n");
console.log(
  `Wrote ${phrases.length} phrases (${freeCount} free, ${FREE_PER_SCENE}/scene) -> ${out}`,
);
